[manager]
ratio = [1, 4, 2]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 200
mouse_events = "click"

[preview]
tab_size = 200
image_filter = "nearest"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
